routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'ProductController@index_general')->name('welcome');
Route::get('/index', 'ProductController@index_general')->name('welcome');


Route::get('/admin', 'AdminController@index')->name('admin.dashboard');
Route::get('/product/{id}', 'ProductController@show_product')->name('product.show');



Route::group(['middleware' => ['auth']], function() {
    Route::resource('admin/roles','RoleController');
    Route::resource('admin/users','UserController');
    Route::resource('admin/products','ProductController');
    Route::resource('admin/categories','CategoryController');
});

Route::resource('comments','CommentController');

Route::get('cart', 'ProductController@cart');
Route::get('add-to-cart/{id}', 'ProductController@addToCart');
Route::get('update-cart/{id}', 'ProductController@updateCart');
Route::get('remove-from-cart/{id}', 'ProductController@removeCart');

//Route::get('/productimage/{filename}', [
//    'uses' => 'ProductController@getProductImage',
//    'as' => 'product.image'
//]);

Route::get('/productimage/{filename}', 'ProductController@getProductImage')->name('product.image');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Product extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = [
        'name', 'viscosity', 'category_id', 'in_stock', 'price'
    ];

    public function comments()
    {
        return $this->hasMany(Comment::class)->whereNull('parent_id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;


use App\Product;
use App\Category;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
//use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;


class ProductController extends Controller
{
/**
* Display a listing of the resource.
*
* @return \Illuminate\Http\Response
*/
function __construct()
{
$this->middleware('permission:product-list', ['only' => ['index']]);
$this->middleware('permission:product-create', ['only' => ['create','store']]);
$this->middleware('permission:product-edit', ['only' => ['edit','update']]);
$this->middleware('permission:product-delete', ['only' => ['destroy']]);
}
/**
* Display a listing of the resource.
*
* @return \Illuminate\Http\Response
*/
public function index()
{
    $products = Product::latest()->paginate(5);
    return view('admin.products.index',compact('products'))
    ->with('i', (request()->input('page', 1) - 1) * 5);
}


    public function index_general()
    {
        $products = Product::latest()->paginate(6);
        return view('welcome',compact('products'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }


/**
* Show the form for creating a new resource.
*
* @return \Illuminate\Http\Response
*/
public function create()
{
    $categories = Category::all();

    return view('admin.products.create', compact('categories'));
}


/**
* Store a newly created resource in storage.
*
* @param  \Illuminate\Http\Request  $request
* @return \Illuminate\Http\Response
*/
public function store(Request $request)
{
request()->validate([
'name' => 'required',
'viscosity' => 'required',
'category_id' => 'required',
'in_stock' => 'required',
'price' => 'required',
]);


Product::create($request->all());


return redirect()->route('products.index')
->with('success','Product created successfully.');
}


/**
* Display the specified resource.
*
* @param  \App\Product  $product
* @return \Illuminate\Http\Response
*/
public function show(Product $product)
{
    $categories = Category::where('id', $product->category_id)->get();
    return view('admin.products.show',compact('product', 'categories'));

}

public function show_product($product)
{
    $product = Product::find($product);
    if(!$product){
        return abort(404);

    }
    $categories = Category::where('id', $product->category_id)->get();

    return view('products.show', compact('product', 'categories'));

}

/**
* Show the form for editing the specified resource.
*
* @param  \App\Product  $product
* @return \Illuminate\Http\Response
*/
public function edit(Product $product)
{
    $categories = Category::all();
    return view('admin.products.edit',compact('product','categories'));
}


/**
* Update the specified resource in storage.
*
* @param  \Illuminate\Http\Request  $request
* @param  \App\Product  $product
* @return \Illuminate\Http\Response
*/
public function update(Request $request, Product $product)
{
    request()->validate([
    'name' => 'required',
    'viscosity' => 'required',
    'category_id' => 'required',
    'in_stock' => 'required',
    'price' => 'required',
]);


    $product->update($request->all());

    $file = $request->file('image');
    $filename = $product->id . '.jpg';

    if ($file) {

        $file->storeAs('images', $filename);

    }

    return redirect()->route('products.index')
        ->with('success','Product updated successfully');
}


public function destroy(Product $product)
{
    $product->delete();
    return redirect()->route('products.index')
    ->with('success','Product deleted successfully');
}

public function cart(){
    return view('products.cart');
}
public function addToCart($id){

    $product = Product::find($id);

    if(!$product) {

        abort(404);

    }

    $cart = session()->get('cart');

    // if cart is empty then this the first product
    if(!$cart) {

        $cart = [
            $id => [
                "name" => $product->name,
                "quantity" => 1,
                "price" => $product->price
            ]
        ];

        session()->put('cart', $cart);

        return redirect()->back()->with('success', 'Product added to cart successfully!');
    }

    // if cart not empty then check if this product exist then increment quantity
    if(isset($cart[$id])) {

        $cart[$id]['quantity']++;

        session()->put('cart', $cart);

        return redirect()->back()->with('success', 'Product added to cart successfully!');

    }

    // if item not exist in cart then add to cart with quantity = 1
    $cart[$id] = [
        "name" => $product->name,
        "quantity" => 1,
        "price" => $product->price
    ];

    session()->put('cart', $cart);

    return redirect()->back()->with('success', 'Product added to cart successfully!');
}

    public function updateCart(Request $request)
    {
        if($request->id and $request->quantity)
        {
            $cart = session()->get('cart');

            $cart[$request->id]["quantity"] = $request->quantity;

            session()->put('cart', $cart);

//            session()->flash('success', 'Cart updated successfully');
            return redirect()->back()->with('success', 'Cart updated successfully');

        }else {
            echo 'erorr!';
        }
    }

    public function removeCart(Request $request)
    {
        if($request->id) {

            $cart = session()->get('cart');

            if(isset($cart[$request->id])) {

                unset($cart[$request->id]);

                session()->put('cart', $cart);
            }

//            session()->flash('success', 'Product removed successfully');
            return redirect()->back()->with('success', 'Product remove successfully!');

        }
    }

    public function getProductImage($filename)
    {
        $file = Storage::disk('local')->get("images/".$filename);

        return new Response($file, 200);

    }

}

resources/views/admin/products/create.blade.php
@extends('adminlte::page')

@section('title', 'Add New Product')

@section('content_header')
    <h1>Add New Product</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
                <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>
        </div>
    </div>


    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('products.store') }}" method="POST">
        @csrf


        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Viscosity:</strong>
                    <input type="text" name="viscosity" class="form-control" placeholder="Viscosity">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Category ID:</strong>
                    <select name="category_id" class="form-control">
                            @foreach($categories as $category)
                                <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach
                        </select>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>In stock:</strong>
                    <input type="text" name="in_stock" class="form-control" placeholder="In Stock">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Price:</strong>
                    <input type="text" name="price" class="form-control" placeholder="Price">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>


    </form>


@endsection

resources/views/admin/products/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Product')

@section('content_header')
    <h1>Edit Product</h1>
@stop


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
                <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>
        </div>
    </div>


    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

<div class="row">
    <div class="col-md-9">
    <form action="{{ route('products.update',$product->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')


        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $product->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Viscosity:</strong>
                    <input type="text" name="viscosity" value="{{ $product->viscosity }}" class="form-control" placeholder="Viscosity">

                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Category:</strong>
                    <select name="category_id" class="form-control">
                        @foreach($categories as $category)
                            <option value="{{$category->id}}">{{$category->name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>In stock:</strong>
                    <input type="text" name="in_stock" value="{{ $product->in_stock }}" class="form-control" placeholder="in_stock">

                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Price:</strong>
                    <input type="text" name="price" value="{{ $product->price }}" class="form-control" placeholder="Price">

                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <label for="image">Image (only .jpg)</label>
                <input type="file" name="image" class="form-control" id="image">
            </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>


    </form>
</div>
    <div class="col-md-3 text-center">
        <label for="#">Product img</label>

    @if(Storage::exists('images/'.$product->id . '.jpg'))
                <img src="{{ route('product.image', ['filename' => $product->id . '.jpg']) }}" alt="" class="img-responsive card-product-info">
            @endif
    </div>
</div>

@endsection

resources/views/admin/products/index.blade.php
@extends('adminlte::page')

@section('title', 'Products')

@section('content_header')
    <h1>Products</h1>
@stop


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
                @can('product-create')
                    <a class="btn btn-success" href="{{ route('products.create') }}"> Create New Product</a>
                @endcan
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Viscosity</th>
            <th>Category</th>
            <th>In stock</th>
            <th>Price</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($products as $product)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $product->name }}</td>
                <td>{{ $product->viscosity }}</td>
                <td>{{ $product->category_id }}</td>
                <td>{{ $product->in_stock }}</td>
                <td>{{ $product->price }}</td>
                <td>
                    <form action="{{ route('products.destroy',$product->id) }}" method="POST">
                        <a class="btn btn-info" href="{{ route('products.show',$product->id) }}">Show</a>
                        @can('product-edit')
                            <a class="btn btn-primary" href="{{ route('products.edit',$product->id) }}">Edit</a>
                        @endcan


                        @csrf
                        @method('DELETE')
                        @can('product-delete')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        @endcan
                    </form>
                </td>
            </tr>
        @endforeach
    </table>


    {!! $products->links() !!}


{{--@endsection--}}
@stop

resources/views/admin/products/show.blade.php
@extends('adminlte::page')

@section('title', 'Show Product')

@section('content_header')
    <h1>Show Product</h1>
@stop


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
                <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $product->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Viscosity:</strong>
                {{ $product->viscosity }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Category:</strong>
                @foreach($categories as $category)
                    {{$category->name}}
                @endforeach
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>In Stock:</strong>
                {{ $product->in_stock }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Price:</strong>
                {{ $product->price }}
            </div>
        </div>
    </div>
@endsection