routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'ProductController@index_general')->name('welcome');
Route::get('/index', 'ProductController@index_general')->name('welcome');


Route::get('/admin', 'AdminController@index')->name('admin.dashboard');
Route::get('/product/{id}', 'ProductController@show_product')->name('product.show');



Route::group(['middleware' => ['auth']], function() {
    Route::resource('admin/roles','RoleController');
    Route::resource('admin/users','UserController');
    Route::resource('admin/products','ProductController');
    Route::resource('admin/categories','CategoryController');
});

Route::resource('comments','CommentController');

Route::get('cart', 'ProductController@cart');
Route::get('add-to-cart/{id}', 'ProductController@addToCart');
Route::get('update-cart/{id}', 'ProductController@updateCart');
Route::get('remove-from-cart/{id}', 'ProductController@removeCart');

//Route::get('/productimage/{filename}', [
//    'uses' => 'ProductController@getProductImage',
//    'as' => 'product.image'
//]);

Route::get('/productimage/{filename}', 'ProductController@getProductImage')->name('product.image');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Product extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = [
        'name', 'viscosity', 'category_id', 'in_stock', 'price'
    ];

    public function comments()
    {
        return $this->hasMany(Comment::class)->whereNull('parent_id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;


use App\Product;
use App\Category;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
//use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;


class ProductController extends Controller
{
/**
* Display a listing of the resource.
*
* @return \Illuminate\Http\Response
*/
function __construct()
{
$this->middleware('permission:product-list', ['only' => ['index']]);
$this->middleware('permission:product-create', ['only' => ['create','store']]);
$this->middleware('permission:product-edit', ['only' => ['edit','update']]);
$this->middleware('permission:product-delete', ['only' => ['destroy']]);
}
/**
* Display a listing of the resource.
*
* @return \Illuminate\Http\Response
*/
public function index()
{
    $products = Product::latest()->paginate(5);
    return view('admin.products.index',compact('products'))
    ->with('i', (request()->input('page', 1) - 1) * 5);
}


    public function index_general()
    {
        $products = Product::latest()->paginate(6);
        return view('welcome',compact('products'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }


/**
* Show the form for creating a new resource.
*
* @return \Illuminate\Http\Response
*/
public function create()
{
    $categories = Category::all();

    return view('admin.products.create', compact('categories'));
}


/**
* Store a newly created resource in storage.
*
* @param  \Illuminate\Http\Request  $request
* @return \Illuminate\Http\Response
*/
public function store(Request $request)
{
request()->validate([
'name' => 'required',
'viscosity' => 'required',
'category_id' => 'required',
'in_stock' => 'required',
'price' => 'required',
]);


Product::create($request->all());


return redirect()->route('products.index')
->with('success','Product created successfully.');
}


/**
* Display the specified resource.
*
* @param  \App\Product  $product
* @return \Illuminate\Http\Response
*/
public function show(Product $product)
{
    $categories = Category::where('id', $product->category_id)->get();
    return view('admin.products.show',compact('product', 'categories'));

}

public function show_product($product)
{
    $product = Product::find($product);
    if(!$product){
        return abort(404);

    }
    $categories = Category::where('id', $product->category_id)->get();

    return view('products.show', compact('product', 'categories'));

}

/**
* Show the form for editing the specified resource.
*
* @param  \App\Product  $product
* @return \Illuminate\Http\Response
*/
public function edit(Product $product)
{
    $categories = Category::all();
    return view('admin.products.edit',compact('product','categories'));
}


/**
* Update the specified resource in storage.
*
* @param  \Illuminate\Http\Request  $request
* @param  \App\Product  $product
* @return \Illuminate\Http\Response
*/
public function update(Request $request, Product $product)
{
    request()->validate([
    'name' => 'required',
    'viscosity' => 'required',
    'category_id' => 'required',
    'in_stock' => 'required',
    'price' => 'required',
]);


    $product->update($request->all());

    $file = $request->file('image');
    $filename = $product->id . '.jpg';

    if ($file) {

        $file->storeAs('images', $filename);

    }

    return redirect()->route('products.index')
        ->with('success','Product updated successfully');
}


public function destroy(Product $product)
{
    $product->delete();
    return redirect()->route('products.index')
    ->with('success','Product deleted successfully');
}

public function cart(){
    return view('products.cart');
}
public function addToCart($id){

    $product = Product::find($id);

    if(!$product) {

        abort(404);

    }

    $cart = session()->get('cart');

    // if cart is empty then this the first product
    if(!$cart) {

        $cart = [
            $id => [
                "name" => $product->name,
                "quantity" => 1,
                "price" => $product->price
            ]
        ];

        session()->put('cart', $cart);

        return redirect()->back()->with('success', 'Product added to cart successfully!');
    }

    // if cart not empty then check if this product exist then increment quantity
    if(isset($cart[$id])) {

        $cart[$id]['quantity']++;

        session()->put('cart', $cart);

        return redirect()->back()->with('success', 'Product added to cart successfully!');

    }

    // if item not exist in cart then add to cart with quantity = 1
    $cart[$id] = [
        "name" => $product->name,
        "quantity" => 1,
        "price" => $product->price
    ];

    session()->put('cart', $cart);

    return redirect()->back()->with('success', 'Product added to cart successfully!');
}

    public function updateCart(Request $request)
    {
        if($request->id and $request->quantity)
        {
            $cart = session()->get('cart');

            $cart[$request->id]["quantity"] = $request->quantity;

            session()->put('cart', $cart);

//            session()->flash('success', 'Cart updated successfully');
            return redirect()->back()->with('success', 'Cart updated successfully');

        }else {
            echo 'erorr!';
        }
    }

    public function removeCart(Request $request)
    {
        if($request->id) {

            $cart = session()->get('cart');

            if(isset($cart[$request->id])) {

                unset($cart[$request->id]);

                session()->put('cart', $cart);
            }

//            session()->flash('success', 'Product removed successfully');
            return redirect()->back()->with('success', 'Product remove successfully!');

        }
    }

    public function getProductImage($filename)
    {
        $file = Storage::disk('local')->get("images/".$filename);

        return new Response($file, 200);

    }

}

resources/views/products/cart.blade.php
@extends('layouts.app')
@section('title', 'Cart')

@section('content')
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <table id="cart" class="table table-hover table-condensed">
        <thead>
        <tr>
            <th style="width:50%">Product</th>
            <th style="width:10%">Price</th>
            <th style="width:8%">Quantity</th>
            <th style="width:22%" class="text-center">Subtotal</th>
            <th style="width:10%"></th>
        </tr>
        </thead>
        <tbody>

        <?php $total = 0 ?>

        @if(session('cart'))
            @foreach(session('cart') as $id => $details)

                <?php $total += $details['price'] * $details['quantity'] ?>

                <tr>
                    <td data-th="Product">
                        <div class="row">
                            <div class="col-sm-3 hidden-xs">
{{--                                <img src="{{ $details['photo'] }}" width="100" height="100" class="img-responsive"/>--}}
                            </div>
                            <div class="col-sm-9">
                                <h4 class="nomargin">{{ $details['name'] }}</h4>
                            </div>
                        </div>
                    </td>
                    <td data-th="Price">${{ $details['price'] }}</td>
                    <td data-th="Quantity">
                        <input type="number" value="{{ $details['quantity'] }}" class="form-control quantity" />
                    </td>
                    <td data-th="Subtotal" class="text-center">${{ $details['price'] * $details['quantity'] }}</td>
                    <td class="actions" data-th="">
{{--                        <button class="btn btn-info btn-sm update-cart" data-id="{{ $id }}"><i class="fa fa-refresh"></i></button>--}}
                        <a href="{{url('update-cart/'.$id)}}" class="btn btn-info btn-sm"><i class="fa fa-refresh"></i></a>

                        {{--                        <button class="btn btn-danger btn-sm remove-from-cart" data-id="{{ $id }}"><i class="fa fa-trash-o"></i></button>--}}
                        <a href="{{url('remove-from-cart/'.$id)}}" class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></a>

                    </td>
                </tr>
            @endforeach
        @endif

        </tbody>
        <tfoot>
        <tr>
            <td><a href="{{ url('/') }}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
            <td colspan="2" class="hidden-xs"></td>
            <td class="hidden-xs text-center"><strong>Total ${{ $total }}</strong></td>
        </tr>
        </tfoot>
    </table>

@endsection

resources/views/products/commentsDisplay.blade.php
@foreach($comments as $comment)
    <div class="display-comment" @if($comment->parent_id != null) style="margin-left:40px;" @endif>
        <strong>{{ $comment->user->name }}</strong>
        <p>{{ $comment->body }}</p>
        <a href="" id="reply"></a>

        @auth

        <form method="post" action="{{ route('comments.store') }}">
            @csrf
            <div class="form-group">
                <input type="text" name="body" class="form-control" />
                <input type="hidden" name="post_id" value="{{ $product_id }}" />
                <input type="hidden" name="parent_id" value="{{ $comment->id }}" />
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-warning" value="Reply" />
            </div>
        </form>
        @endauth

        @guest
            <hr>
        @endguest



        @include('products.commentsDisplay', ['comments' => $comment->replies])
    </div>
@endforeach

resources/views/products/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        @include('sidebar')
    <div class="col">
    <div class="card-product">
        <div class="container">
            <div class="wrapper row">
                <div class="preview col-md-6">

                    <div class="preview-pic tab-content">
                        <div class="tab-pane active text-center" id="pic-1">

                            @if(Storage::exists('images/'.$product->id . '.jpg'))
                                <img src="{{ route('product.image', ['filename' => $product->id . '.jpg']) }}" alt="" class="img-responsive card-product-info">

                            @else <img class="img-responsive" src="http://placekitten.com/400/400" alt="Card image cap">
                            @endif

{{--                            <img src="http://placekitten.com/400/252" />--}}

                        </div>
{{--                        <div class="tab-pane" id="pic-2"><img src="http://placekitten.com/400/252" /></div>--}}
{{--                        <div class="tab-pane" id="pic-3"><img src="http://placekitten.com/400/252" /></div>--}}
{{--                        <div class="tab-pane" id="pic-4"><img src="http://placekitten.com/400/252" /></div>--}}
{{--                        <div class="tab-pane" id="pic-5"><img src="http://placekitten.com/400/252" /></div>--}}
                    </div>
{{--                    <ul class="preview-thumbnail nav nav-tabs">--}}
{{--                        <li class="active"><a data-target="#pic-1" data-toggle="tab"><img src="http://placekitten.com/200/126" /></a></li>--}}
{{--                        <li><a data-target="#pic-2" data-toggle="tab"><img src="http://placekitten.com/200/126" /></a></li>--}}
{{--                        <li><a data-target="#pic-3" data-toggle="tab"><img src="http://placekitten.com/200/126" /></a></li>--}}
{{--                        <li><a data-target="#pic-4" data-toggle="tab"><img src="http://placekitten.com/200/126" /></a></li>--}}
{{--                        <li><a data-target="#pic-5" data-toggle="tab"><img src="http://placekitten.com/200/126" /></a></li>--}}
{{--                    </ul>--}}

                </div>
                <div class="details col-md-6">
                    <h3 class="product-title"> {{ $product->name }}</h3>
                    <div class="rating">
                        <div class="stars">
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                        </div>
                        <span class="review-no">41 <a href="#">comments</a></span>
                    </div>
{{--                    <p class="product-description">Suspendisse quos? Tempus cras iure temporibus? Eu laudantium cubilia sem sem! Repudiandae et! Massa senectus enim minim sociosqu delectus posuere.</p>--}}
                    <h4 class="price">Price: <span>{{ $product->price }} UAH</span></h4>
                    <h4>Viscosity: <a href="#">{{ $product->viscosity }}</a></h4>
                    <h4>Category:
                        @foreach($categories as $category)
                            <a href="#"> {{$category->name}}</a>
                        @endforeach
                    </h4>
                    <div class="action">
                        <a href="{{ url('add-to-cart/'.$product->id) }}" class="add-to-cart btn btn-default" type="button">add to cart</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
        <br>
        <div class="row">
            <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4>Display Comments</h4>
            </div>
            <div class="card-body">
            @include('products.commentsDisplay', ['comments' => $product->comments, 'product_id' => $product->id])

            @auth
                    <hr />

                    <h4>Add comment</h4>

                    <form method="post" action="{{ route('comments.store'   ) }}">
                @csrf
                <div class="form-group">
                    <textarea class="form-control" name="body"></textarea>
                    <input type="hidden" name="product_id" value="{{ $product->id }}" />
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success" value="Add Comment" />
                </div>
            </form>
            @endauth
            @guest
               <div class="alert alert-info"><a href="{{ route('login') }}">Авторизуйтесь</a>, чтобы комментировать</div>
            @endguest
        </div>
        </div>
        </div>
        </div>
    </div>
    </div>

@endsection