routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'ProductController@index_general')->name('welcome');
Route::get('/index', 'ProductController@index_general')->name('welcome');


Route::get('/admin', 'AdminController@index')->name('admin.dashboard');
Route::get('/product/{id}', 'ProductController@show_product')->name('product.show');



Route::group(['middleware' => ['auth']], function() {
    Route::resource('admin/roles','RoleController');
    Route::resource('admin/users','UserController');
    Route::resource('admin/products','ProductController');
    Route::resource('admin/categories','CategoryController');
});

Route::resource('comments','CommentController');

Route::get('cart', 'ProductController@cart');
Route::get('add-to-cart/{id}', 'ProductController@addToCart');
Route::get('update-cart/{id}', 'ProductController@updateCart');
Route::get('remove-from-cart/{id}', 'ProductController@removeCart');

//Route::get('/productimage/{filename}', [
//    'uses' => 'ProductController@getProductImage',
//    'as' => 'product.image'
//]);

Route::get('/productimage/{filename}', 'ProductController@getProductImage')->name('product.image');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name'
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    function __construct()
    {
        $this->middleware('permission:category-list');
        $this->middleware('permission:category-create', ['only' => ['create','store']]);
        $this->middleware('permission:category-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:category-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::latest()->paginate(5);
        return view('admin.categories.index',compact('categories'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();

        return view('admin.categories.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required',
        ]);


        Category::create($request->all());


        return redirect()->route('categories.index')
            ->with('success','Category created successfully.');    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('admin.categories.show',compact('category'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit',compact('category'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {

        request()->validate([
            'name' => 'required',
        ]);


        $category->update($request->all());


        return redirect()->route('categories.index')
            ->with('success','Category updated successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();


        return redirect()->route('categories.index')
            ->with('success','Product deleted successfully');

    }
}

resources/views/admin/categories/create.blade.php
@extends('adminlte::page')

@section('title', 'Add New Category')

@section('content_header')
    <h1>Add New Category</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
                <a class="btn btn-primary" href="{{ route('categories.index') }}"> Back</a>
        </div>
    </div>


    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('categories.store') }}" method="POST">
        @csrf


        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>


    </form>


@endsection

resources/views/admin/categories/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Category')

@section('content_header')
    <h1>Edit Category</h1>
@stop


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
                <a class="btn btn-primary" href="{{ route('categories.index') }}"> Back</a>
        </div>
    </div>


    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('categories.update',$category->id) }}" method="POST">
        @csrf
        @method('PUT')


        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $category->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>


    </form>


@endsection

resources/views/admin/categories/index.blade.php
@extends('adminlte::page')

@section('title', 'Categories')

@section('content_header')
    <h1>Categories</h1>
@stop


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
                @can('category-create')
                    <a class="btn btn-success" href="{{ route('categories.create') }}"> Create New Category</a>
                @endcan
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>

            <th width="280px">Action</th>
        </tr>
        @foreach ($categories as $category)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $category->name }}</td>
                <td>
                    <form action="{{ route('products.destroy',$category->id) }}" method="POST">
                        <a class="btn btn-info" href="{{ route('categories.show',$category->id) }}">Show</a>
                        @can('category-edit')
                            <a class="btn btn-primary" href="{{ route('categories.edit',$category->id) }}">Edit</a>
                        @endcan


                        @csrf
                        @method('DELETE')
                        @can('category-delete')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        @endcan
                    </form>
                </td>
            </tr>
        @endforeach
    </table>


    {!! $categories->links() !!}


{{--@endsection--}}
@stop

resources/views/admin/categories/show.blade.php
@extends('adminlte::page')

@section('title', 'Show Category')

@section('content_header')
    <h1>Show Category</h1>
@stop


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
                <a class="btn btn-primary" href="{{ route('categories.index') }}"> Back</a>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $category->name }}
            </div>
        </div>
    </div>
@endsection